version: '3.8'

volumes:
  app-data: {}

services:
  app:
    build: .
    image: frodan/bot_respect:latest
    environment:
      - TELEGRAM_API_KEY=${$TG_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_ROLE=${DB_ROLE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=respect
    depends_on:
      - db_postgres
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 100M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
    
  db_postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
        - "5432:5432"
    volumes:
        - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db:
    driver: local
  pgadmin-data:
    driver: local